[package]
name = "cargo-bazel"
version = "0.0.3"
authors = [
    "UebelAndre - github@uebelandre.com",
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
cargo_metadata = "0.14.0"
cargo_toml = "0.10.1"
cargo-lock = "7.0.1"
cargo-platform = "0.1.2"
cfg-expr = "0.9.0"
hex = "0.4.3"
pathdiff = "0.2.0"
regex = "1.5.4"
semver = "1.0.4"
serde = "1.0.129"
serde_json = "1.0.66"
sha2 = "0.9.8"
structopt = "0.3.22"
tera = "1.13.0"
textwrap = "0.14.2"
toml = "0.5.8"

# WIP
# https://github.com/frewsxcv/rust-crates-index/issues/64
# This may require that `git2` disable any dependencies on OpenSSL or system packages
# crates-index = "0.17.0"

[dev-dependencies]
tempfile = "3.2.0"
